# 服务启动端口号
server:
  port: 8088
  servlet:
    context-path: /tobbyblog
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tobby_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # 编码
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
mybatis:
  mapper-locations: classpath:mappings/*Mapper.xml
  type-aliases-package: com.jiangtong.entity

#showSql
logging:
  level:
    com:
      jiangtong: debug
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
    count: countSql
